import Head from "next/head";
import React from "react";

const admin = () => {
  return (
    <>
      <Head>
<<<<<<< HEAD
        <title>GURU-COOL : ADMIN LOGIN</title>
=======
        <title>GURU COOL : ADMIN LOGIN</title>
>>>>>>> 41537e571f66ba17ab2404a4017093443e58fc17
        <meta
          name="description"
          content="Generated by developer for the who needs to be thier doubts and want to learn from the expert"
        />
        <link rel="icon" href="/images/logo.png" />
      </Head>
      <div className="bg-pink-200 h-screen w-screen flex items-center justify-center">
        <div className="bg-pink-400 rounded-md shadow-2xl p-20">
          heelo
        </div>
      </div>
    </>
  );
};

export default admin;
