import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
<<<<<<< HEAD
        <title>GURU-COOL</title>
=======
        <title>GURU COOL</title>
>>>>>>> 41537e571f66ba17ab2404a4017093443e58fc17
        <meta name="description" content="Generated by developer for the who needs to be thier doubts and want to learn from the expert" />
        <link rel="icon" href="/images/logo.png" />
      </Head>
    </>
  )
}
