import React from 'react'
import Head from 'next/head'
import Radio from './components/Radio.jsx'

const Register = () => {

  return (
    <>
      <Head>
<<<<<<< HEAD
        <title>GURU-COOL: Registation</title>
=======
        <title>GURU COOL : Registation</title>
>>>>>>> 41537e571f66ba17ab2404a4017093443e58fc17
        <meta name="description" content="Generated by developer for the who needs to be thier doubts and want to learn from the expert" />
        <link rel="icon" href="/images/logo.png" />
      </Head>
      <div className='mb-[15rem]'>
      <Radio/>
      </div>
    </>
  )
}

export default Register